// <auto-generated />
using System;
using BillingManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillingManagement.Infrastructure.Migrations
{
    [DbContext(typeof(BillingManagementDbContext))]
    [Migration("20260722095037_AddOwnerCompanyProfileCoverMedia")]
    partial class AddOwnerCompanyProfileCoverMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillingManagement.Domain.OwnerCompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CityProvinceState")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CoverStorageKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("LogoReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("SingletonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("TaxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.ToTable("OwnerCompanyProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_AddressLine1_NotBlank", "LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [AddressLine1])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_AddressLine2_NotBlank", "[AddressLine2] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [AddressLine2])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_CityProvinceState_NotBlank", "LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [CityProvinceState])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_CompanyName_NotBlank", "LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [CompanyName])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_Country_NotBlank", "LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [Country])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_CoverContentType_NotBlank", "[CoverContentType] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [CoverContentType])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_CoverStorageKey_NotBlank", "[CoverStorageKey] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [CoverStorageKey])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_Email_NotBlank", "[Email] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [Email])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_LogoReference_NotBlank", "[LogoReference] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [LogoReference])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_Phone_NotBlank", "[Phone] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [Phone])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_PostalCode_NotBlank", "LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [PostalCode])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_RegistrationNumber_NotBlank", "[RegistrationNumber] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [RegistrationNumber])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_SingletonKey", "[SingletonKey] = 1");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_TaxId_NotBlank", "[TaxId] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [TaxId])) > 0");

                            t.HasCheckConstraint("CK_OwnerCompanyProfiles_Website_NotBlank", "[Website] IS NULL OR LEN(TRIM(N' ' + NCHAR(9) + NCHAR(10) + NCHAR(11) + NCHAR(12) + NCHAR(13) + NCHAR(160) FROM [Website])) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
