using BillingManagement.Application.Abstractions.OwnerCompanyProfiles;
using BillingManagement.Application.Abstractions.Queries;

namespace BillingManagement.Application.OwnerCompanyProfiles.GetOwnerCompanyProfile;

public sealed record GetOwnerCompanyProfileQuery : IQuery<GetOwnerCompanyProfileResult>;
